#!/usr/bin/env bash

shopt -s nullglob globstar

# Variables
black="#1E1E2E" 
sky="#89DCEB"
mauve="#DDB6F2" 
peach="#F8BD96"
green="#ABE9B3"
purple="#A163B2"
pink="#F2BEFC"

stringContain() { [ -z "$1" ] || { [ -z "${2##*$1*}" ] && [ -n "$2" ];};}

menu() { bemenu --prefix '' --prompt 'apps' --list 7 --fn 'monospace 10' --tb $black --ab $black --af "#4FB0ED" --tf $sky --fb $black --ff "#E856A0" --nb $black --nf "#4FB0ED" --hb $black --hf $sky; }

prefix=${PASSWORD_STORE_DIR-~/.password-store}
password_files=( "$prefix"/**/*.gpg )
password_files=( "${password_files[@]#"$prefix"/}" )
password_files=( "${password_files[@]%.gpg}" )

password=$(printf '%s\n' "${password_files[@]}" | menu "$@")

[[ -n $password ]] || exit

pass show -c "$password" 2>/dev/null
